const BASE=window.APP_CONFIG.FIREBASE_URL.replace(/\/$/,"");
let co2Chart,tempChart,humChart;
const $=id=>document.getElementById(id);
function state(v){if(v<800)return["Добро качество на въздуха","#39d98a"];if(v<1200)return["Препоръчва се проветряване","#ffd166"];if(v<1600)return["Високо ниво — проветрете","#ff9f43"];return["Много високо ниво — проветрете веднага","#ff6b6b"]}
function fmt(ts){return ts?new Date(ts*1000).toLocaleString("bg-BG",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}):"—"}
function baseOptions(){return{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:"#edf5ff"}}},scales:{x:{ticks:{color:"#9db1cb",maxTicksLimit:8},grid:{color:"rgba(255,255,255,.05)"}},y:{ticks:{color:"#9db1cb"},grid:{color:"rgba(255,255,255,.08)"}}}}}
function lineChart(canvas,label,values,color,fill=false){return new Chart($(canvas),{type:"line",data:{labels:window.chartLabels,datasets:[{label,data:values,borderColor:color,backgroundColor:fill?color.replace("#39d98a","rgba(57,217,138,.14)"):"transparent",fill,tension:.3,pointRadius:2,borderWidth:3}]},options:baseOptions()})}
function render(current,raw){const c=Number(current?.co2||0),t=Number(current?.temperature||0),h=Number(current?.humidity||0);$("co2").innerHTML=c?`${c} <span class="unit">ppm</span>`:`—`;$("temp").innerHTML=t?`${t.toFixed(1)} <span class="unit">°C</span>`:`—`;$("hum").innerHTML=h?`${h.toFixed(1)} <span class="unit">%</span>`:`—`;const s=state(c);$("state").textContent=c?s[0]:"Очакване на данни";$("state").style.color=s[1];$("updated").textContent=`Последно обновяване: ${fmt(current?.updated_at)}`;const online=Boolean(current&&current.co2!==undefined);$("dot").classList.toggle("on",online);$("conn").textContent=online?"Устройството е онлайн":"Няма данни от устройството";const min=Math.floor(Date.now()/1000)-12*60*60;const data=Object.values(raw||{}).filter(x=>x?.timestamp>=min).sort((a,b)=>a.timestamp-b.timestamp);window.chartLabels=data.map(x=>new Date(x.timestamp*1000).toLocaleTimeString("bg-BG",{hour:"2-digit",minute:"2-digit"}));if(co2Chart)co2Chart.destroy();if(tempChart)tempChart.destroy();if(humChart)humChart.destroy();co2Chart=lineChart("co2Chart","CO₂ ppm",data.map(x=>x.co2),"#39d98a",true);tempChart=lineChart("tempChart","Температура °C",data.map(x=>x.temperature),"#ffd166");humChart=lineChart("humChart","Влажност %",data.map(x=>x.humidity),"#3ba7ff");$("err").textContent=data.length<2?"За линиите са нужни поне две исторически точки; ESP32 записва по една на 5 минути.":""}
async function load(){try{const[a,b]=await Promise.all([fetch(`${BASE}/co2_monitor/current.json`),fetch(`${BASE}/co2_monitor/history.json`)]);render(await a.json(),await b.json())}catch(e){$("dot").classList.remove("on");$("conn").textContent="Грешка при Firebase връзката";$("err").textContent=e.message;console.error(e)}}
load();setInterval(load,15000);